### ISSUE TITLE
SpaCy ARN - Validation error due to Regular Expression

### ISSUE THREAD

**Issue by adriaanbd** [keithrozario/Klayers#110]
**Describe the bug**
When deploying a SpaCy and SpaCy model Lambda Layer with CloudFormation, there's a validation error for regular expression pattern.

```
    SpaCyLayer:
        Type: AWS::Lambda::LayerVersion
        Properties:
            Description: SpaCy module
            LayerName: !Sub arn:aws:lambda:${AWS::Region}:770693421928:layer:Klayers-python38-spacy:24

    SpaCyEngModel:
        Type: AWS::Lambda::LayerVersion
        Properties:
            Description: Small english model for SpaCy
            LayerName: !Sub arn:aws:lambda:${AWS::Region}:770693421928:layer:Klayers-python38-spacy_model_en_small:1
```

**Screenshots**
![image](https://user-images.githubusercontent.com/22228397/91117348-fd9fbe00-e653-11ea-9871-816209b01037.png)

**Layer Version ARN:**
arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-spacy:24
arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-spacy_model_en_small:1

**Framework:**
AWS CLI with CloudFormation

**Additional context**
This is executed with `aws cloudformation package` then `aws cloudformation deploy` due to local file path in another part of the script.
